enum Actions {
  NEW_TASK = 'NEW_TASK',
  UPDATE_TASK = 'UPDATE_TASK',
  COMPLETE_TASK = 'COMPLETE_TASK',
  DELETE_TASK = 'DELETE_TASK',
  SELECT_TASK = 'SELECT_TASK',
  UNSELECT_TASK = 'UNSELECT_TASK',
  SHOW_DIALOG = 'SHOW_DIALOG',
  FETCHING = 'FETCHING',
  GET_TASKS = 'GET_TASKS'
}

export default Actions;
